// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvjgihstixixgfsujykn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52amdpaHN0aXhpeGdmc3VqeWtuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjk0MjgsImV4cCI6MjA2NDYwNTQyOH0.4nUdijovJOSj3g8E2817o1Pb2rE_6R9o0w2cWLZ24cU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);